version: '3.3'
services:
    mongo:
        container_name: uncle-styopa-db
        image: mongo:3.7
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=secret
        ports:
            - "27017:27017"
