export enum EnvVariable {
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  DB_PORT = 'DB_PORT',
  DB_DATABASE = 'DB_DATABASE',
  DB_HOST = 'DB_HOST',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_AUTH_SOURCE = 'DB_AUTH_SOURCE',
  DB_FILES_COLLECTION_PREFIX = 'DB_FILES_COLLECTION_PREFIX',
  HASH_ROUNDS = 'HASH_ROUNDS',
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRATION_TIME = 'JWT_EXPIRATION_TIME',
}
